# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.2.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.2.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jordanwillis/GitRepos/seqig_standalone

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jordanwillis/GitRepos/seqig_standalone

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.2.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.2.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jordanwillis/GitRepos/seqig_standalone/CMakeFiles /Users/jordanwillis/GitRepos/seqig_standalone/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jordanwillis/GitRepos/seqig_standalone/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SeqIg

# Build rule for target.
SeqIg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SeqIg
.PHONY : SeqIg

# fast build rule for target.
SeqIg/fast:
	$(MAKE) -f CMakeFiles/SeqIg.dir/build.make CMakeFiles/SeqIg.dir/build
.PHONY : SeqIg/fast

src/AlignAntibody.o: src/AlignAntibody.cpp.o
.PHONY : src/AlignAntibody.o

# target to build an object file
src/AlignAntibody.cpp.o:
	$(MAKE) -f CMakeFiles/SeqIg.dir/build.make CMakeFiles/SeqIg.dir/src/AlignAntibody.cpp.o
.PHONY : src/AlignAntibody.cpp.o

src/AlignAntibody.i: src/AlignAntibody.cpp.i
.PHONY : src/AlignAntibody.i

# target to preprocess a source file
src/AlignAntibody.cpp.i:
	$(MAKE) -f CMakeFiles/SeqIg.dir/build.make CMakeFiles/SeqIg.dir/src/AlignAntibody.cpp.i
.PHONY : src/AlignAntibody.cpp.i

src/AlignAntibody.s: src/AlignAntibody.cpp.s
.PHONY : src/AlignAntibody.s

# target to generate assembly for a file
src/AlignAntibody.cpp.s:
	$(MAKE) -f CMakeFiles/SeqIg.dir/build.make CMakeFiles/SeqIg.dir/src/AlignAntibody.cpp.s
.PHONY : src/AlignAntibody.cpp.s

src/AntibodyJunction.o: src/AntibodyJunction.cpp.o
.PHONY : src/AntibodyJunction.o

# target to build an object file
src/AntibodyJunction.cpp.o:
	$(MAKE) -f CMakeFiles/SeqIg.dir/build.make CMakeFiles/SeqIg.dir/src/AntibodyJunction.cpp.o
.PHONY : src/AntibodyJunction.cpp.o

src/AntibodyJunction.i: src/AntibodyJunction.cpp.i
.PHONY : src/AntibodyJunction.i

# target to preprocess a source file
src/AntibodyJunction.cpp.i:
	$(MAKE) -f CMakeFiles/SeqIg.dir/build.make CMakeFiles/SeqIg.dir/src/AntibodyJunction.cpp.i
.PHONY : src/AntibodyJunction.cpp.i

src/AntibodyJunction.s: src/AntibodyJunction.cpp.s
.PHONY : src/AntibodyJunction.s

# target to generate assembly for a file
src/AntibodyJunction.cpp.s:
	$(MAKE) -f CMakeFiles/SeqIg.dir/build.make CMakeFiles/SeqIg.dir/src/AntibodyJunction.cpp.s
.PHONY : src/AntibodyJunction.cpp.s

src/DatabaseHandler.o: src/DatabaseHandler.cpp.o
.PHONY : src/DatabaseHandler.o

# target to build an object file
src/DatabaseHandler.cpp.o:
	$(MAKE) -f CMakeFiles/SeqIg.dir/build.make CMakeFiles/SeqIg.dir/src/DatabaseHandler.cpp.o
.PHONY : src/DatabaseHandler.cpp.o

src/DatabaseHandler.i: src/DatabaseHandler.cpp.i
.PHONY : src/DatabaseHandler.i

# target to preprocess a source file
src/DatabaseHandler.cpp.i:
	$(MAKE) -f CMakeFiles/SeqIg.dir/build.make CMakeFiles/SeqIg.dir/src/DatabaseHandler.cpp.i
.PHONY : src/DatabaseHandler.cpp.i

src/DatabaseHandler.s: src/DatabaseHandler.cpp.s
.PHONY : src/DatabaseHandler.s

# target to generate assembly for a file
src/DatabaseHandler.cpp.s:
	$(MAKE) -f CMakeFiles/SeqIg.dir/build.make CMakeFiles/SeqIg.dir/src/DatabaseHandler.cpp.s
.PHONY : src/DatabaseHandler.cpp.s

src/OutputHandler.o: src/OutputHandler.cpp.o
.PHONY : src/OutputHandler.o

# target to build an object file
src/OutputHandler.cpp.o:
	$(MAKE) -f CMakeFiles/SeqIg.dir/build.make CMakeFiles/SeqIg.dir/src/OutputHandler.cpp.o
.PHONY : src/OutputHandler.cpp.o

src/OutputHandler.i: src/OutputHandler.cpp.i
.PHONY : src/OutputHandler.i

# target to preprocess a source file
src/OutputHandler.cpp.i:
	$(MAKE) -f CMakeFiles/SeqIg.dir/build.make CMakeFiles/SeqIg.dir/src/OutputHandler.cpp.i
.PHONY : src/OutputHandler.cpp.i

src/OutputHandler.s: src/OutputHandler.cpp.s
.PHONY : src/OutputHandler.s

# target to generate assembly for a file
src/OutputHandler.cpp.s:
	$(MAKE) -f CMakeFiles/SeqIg.dir/build.make CMakeFiles/SeqIg.dir/src/OutputHandler.cpp.s
.PHONY : src/OutputHandler.cpp.s

src/PropertiesHandler.o: src/PropertiesHandler.cpp.o
.PHONY : src/PropertiesHandler.o

# target to build an object file
src/PropertiesHandler.cpp.o:
	$(MAKE) -f CMakeFiles/SeqIg.dir/build.make CMakeFiles/SeqIg.dir/src/PropertiesHandler.cpp.o
.PHONY : src/PropertiesHandler.cpp.o

src/PropertiesHandler.i: src/PropertiesHandler.cpp.i
.PHONY : src/PropertiesHandler.i

# target to preprocess a source file
src/PropertiesHandler.cpp.i:
	$(MAKE) -f CMakeFiles/SeqIg.dir/build.make CMakeFiles/SeqIg.dir/src/PropertiesHandler.cpp.i
.PHONY : src/PropertiesHandler.cpp.i

src/PropertiesHandler.s: src/PropertiesHandler.cpp.s
.PHONY : src/PropertiesHandler.s

# target to generate assembly for a file
src/PropertiesHandler.cpp.s:
	$(MAKE) -f CMakeFiles/SeqIg.dir/build.make CMakeFiles/SeqIg.dir/src/PropertiesHandler.cpp.s
.PHONY : src/PropertiesHandler.cpp.s

src/SeqIg.o: src/SeqIg.cpp.o
.PHONY : src/SeqIg.o

# target to build an object file
src/SeqIg.cpp.o:
	$(MAKE) -f CMakeFiles/SeqIg.dir/build.make CMakeFiles/SeqIg.dir/src/SeqIg.cpp.o
.PHONY : src/SeqIg.cpp.o

src/SeqIg.i: src/SeqIg.cpp.i
.PHONY : src/SeqIg.i

# target to preprocess a source file
src/SeqIg.cpp.i:
	$(MAKE) -f CMakeFiles/SeqIg.dir/build.make CMakeFiles/SeqIg.dir/src/SeqIg.cpp.i
.PHONY : src/SeqIg.cpp.i

src/SeqIg.s: src/SeqIg.cpp.s
.PHONY : src/SeqIg.s

# target to generate assembly for a file
src/SeqIg.cpp.s:
	$(MAKE) -f CMakeFiles/SeqIg.dir/build.make CMakeFiles/SeqIg.dir/src/SeqIg.cpp.s
.PHONY : src/SeqIg.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SeqIg"
	@echo "... src/AlignAntibody.o"
	@echo "... src/AlignAntibody.i"
	@echo "... src/AlignAntibody.s"
	@echo "... src/AntibodyJunction.o"
	@echo "... src/AntibodyJunction.i"
	@echo "... src/AntibodyJunction.s"
	@echo "... src/DatabaseHandler.o"
	@echo "... src/DatabaseHandler.i"
	@echo "... src/DatabaseHandler.s"
	@echo "... src/OutputHandler.o"
	@echo "... src/OutputHandler.i"
	@echo "... src/OutputHandler.s"
	@echo "... src/PropertiesHandler.o"
	@echo "... src/PropertiesHandler.i"
	@echo "... src/PropertiesHandler.s"
	@echo "... src/SeqIg.o"
	@echo "... src/SeqIg.i"
	@echo "... src/SeqIg.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

